[package]
name = "rust2vec"
version = "0.2.1"
authors = ["Daniël de Kok <me@danieldk.eu>"]
description = "Read/writer for the word2vec binary/text files"
documentation = "https://docs.rs/rust2vec/"
homepage = "https://github.com/danieldk/rust2vec"
repository = "https://github.com/danieldk/rust2vec"
license = "Apache-2.0"
readme = "README.md"
exclude = [
  ".gitignore"
]

[dependencies]
byteorder = "1"
failure = "0.1"
ndarray = "0.9"
itertools = "0.6"
