[package]
name = "rust2vec"
version = "0.5.2"
edition = "2018"
authors = ["Daniël de Kok <me@danieldk.eu>"]
description = "Reader and writer for common word embedding formats"
documentation = "https://docs.rs/rust2vec/"
keywords = ["embeddings", "word2vec", "glove", "finalfusion", "subword"]
homepage = "https://github.com/danieldk/rust2vec"
repository = "https://github.com/danieldk/rust2vec"
license = "Apache-2.0"
readme = "../README.md"
exclude = [
  ".gitignore",
  ".travis.yml"
]

[badges]
maintenance = { status = "deprecated" }

[dependencies]
byteorder = "1"
failure = "0.1"
fnv = "1"
itertools = "0.8"
memmap = "0.7"
ndarray = "0.12"
ordered-float = "1"
rand = "0.6"
rand_xorshift = "0.1"
reductive = "0.2"
toml = "0.4"

[dev-dependencies]
maplit = "1"
lazy_static = "1"
